<a href="https://colab.research.google.com/github/Tchuissi/DATA-690-WANG/blob/master/draft%20assignment%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Assignment 3**#

In [ ]:
import random
import numpy as np

z= np.random.randint(0,10,100)
print(z)
print(type(z))
print(z.shape)

[7 9 8 0 9 4 1 3 2 4 9 8 4 1 8 8 3 9 9 0 1 2 5 3 5 6 5 0 6 0 3 6 8 5 7 3 5
 1 5 0 8 7 7 1 3 3 3 2 2 4 4 6 4 5 4 6 6 1 8 9 0 4 5 8 6 9 5 1 2 3 4 9 9 3
 9 8 8 6 2 1 7 2 0 9 6 3 9 7 7 5 8 5 5 9 8 3 4 3 3 6]
<class 'numpy.ndarray'>
(100,)


In [ ]:
X = z.reshape(10,10)

print("\n",X.shape)
print("\n",X, end="")


 (10, 10)

 [[7 9 8 0 9 4 1 3 2 4]
 [9 8 4 1 8 8 3 9 9 0]
 [1 2 5 3 5 6 5 0 6 0]
 [3 6 8 5 7 3 5 1 5 0]
 [8 7 7 1 3 3 3 2 2 4]
 [4 6 4 5 4 6 6 1 8 9]
 [0 4 5 8 6 9 5 1 2 3]
 [4 9 9 3 9 8 8 6 2 1]
 [7 2 0 9 6 3 9 7 7 5]
 [8 5 5 9 8 3 4 3 3 6]]

In [2]:
row_labels = ['*', '*', '*', '*'] 



In [ ]:
import pandas as pd


In [ ]:
df = pd.DataFrame(x, columns=column_labels, index=row_labels) 

ValueError: ignored